#!/bin/bash

VER="1.4.3"

mvn deploy:deploy-file -DgroupId=rcstadheim -DartifactId=accounting-repos \
    -Dversion=${VER} -Dpackaging=jar -Dfile=build/libs/accounting-repos-${VER}.jar \
    -Durl=file:repo


exit 0
