#!/bin/bash

VER="1.8.3"

mvn deploy:deploy-file -DgroupId=rcstadheim -DartifactId=accounting-repos \
    -Dversion=${VER} -Dpackaging=jar -Dfile=build/libs/accounting-repos-${VER}.jar \
    -Durl=file:/home/rcs/opt/java/mavenlocalrepo


exit 0
